/**
 * Static utility methods for dealing with events.
 */
export default class Events {

    /**
     * Given an event generated by clicking <a href='#something'> return a
     * jquery element referencing the link and a string with the value of
     * the href attribute, minus the '#' character.
     */
    static eventDetail(event) {
        event.preventDefault();
        const link = $(event.target),
            target = link.attr('href') || link.parent().attr('href'),
            actionName = target.replace('#', '');
        return { link, actionName };
    }

}
